# Generated by Django 5.0.6 on 2024-09-17 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vparnter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('adhar_no', models.CharField(max_length=12, unique=True)),
                ('dl', models.CharField(max_length=20, unique=True)),
                ('dl_document', models.FileField(blank=True, null=True, upload_to='dl_documents/')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vparnter.partner')),
            ],
        ),
    ]
