# Generated by Django 5.0.6 on 2024-09-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vparnter', '0002_partnerinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerinfo',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
