# Generated by Django 5.0.6 on 2024-09-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vparnter', '0003_partnerinfo_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerinfo',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
