# Generated by Django 5.0.6 on 2024-09-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vparnter', '0004_partnerinfo_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerinfo',
            name='driver_id',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
