# Generated by Django 5.0.6 on 2024-09-17 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vparnter', '0005_partnerinfo_driver_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicle_photos/')),
                ('load_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rc_card_photo', models.ImageField(blank=True, null=True, upload_to='rc_card_photos/')),
                ('insurance', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vparnter.partnerinfo')),
            ],
        ),
    ]
