# Generated by Django 5.0.6 on 2024-09-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vparnter', '0006_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='owner_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
