# Generated by Django 5.0.6 on 2024-09-18 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vparnter', '0007_vehicle_owner_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerinfo',
            old_name='partner',
            new_name='phone_no',
        ),
    ]
