# Generated by Django 5.0.6 on 2024-09-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vparnter', '0008_rename_partner_partnerinfo_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerinfo',
            old_name='phone_no',
            new_name='partner',
        ),
    ]
