# Generated by Django 5.0.6 on 2024-09-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vparnter', '0009_rename_phone_no_partnerinfo_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_status',
            field=models.CharField(blank=True, choices=[('running', 'Running'), ('standing', 'Standing')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='insurance',
            field=models.FileField(blank=True, null=True, upload_to='insurance_documents/'),
        ),
    ]
