# Generated by Django 5.0.6 on 2024-09-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vparnter', '0010_vehicle_status_vehicle_vehicle_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerinfo',
            name='adhar_no',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
