# Generated by Django 5.0.6 on 2024-09-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vparnter', '0011_alter_partnerinfo_adhar_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='location',
            field=models.CharField(max_length=500),
        ),
    ]
