# Generated by Django 5.0.6 on 2024-09-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vparnter', '0013_pocket_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(choices=[('subscription_fee', 'Subscription Fee'), ('processing_fee', 'Processing Fee')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
