# Generated by Django 5.0.6 on 2024-09-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vparnter', '0014_transaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='district',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='taluk_town',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
