# Generated by Django 5.0.6 on 2024-09-30 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vparnter', '0015_vehicle_district_vehicle_state_vehicle_taluk_town'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_category', models.IntegerField(choices=[(1, '0 to 100 kg'), (2, '0 to 250 kg'), (3, '0 to 650 kg'), (4, '0 to 1000 kg'), (5, '0 to 1500 kg'), (6, '0 to 2000 kg')], unique=True)),
                ('base_price_per_km', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField()),
                ('load_weight', models.FloatField()),
                ('vehicle_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vparnter.vehiclecategory')),
            ],
        ),
        migrations.CreateModel(
            name='LoadPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_usage', models.CharField(max_length=20)),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vehicle_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vparnter.vehiclecategory')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vparnter.vehiclecategory'),
        ),
    ]
