# Generated by Django 5.0.6 on 2024-10-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vparnter', '0016_vehiclecategory_pricing_loadpricing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_purpose',
            field=models.CharField(choices=[('passenger', 'Passenger'), ('logistics', 'Logistics')], default='logistics', max_length=10),
        ),
    ]
