# Generated by Django 5.0.6 on 2024-10-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vparnter', '0017_vehicle_vehicle_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecategory',
            name='weight_category',
            field=models.IntegerField(choices=[(1, '0 to 100 kg'), (2, '0 to 250 kg'), (3, '0 to 650 kg'), (4, '0 to 1000 kg'), (5, '0 to 1500 kg'), (6, '0 to 2000 kg'), (7, 'Passenger')], unique=True),
        ),
    ]
