# Generated by Django 5.0.6 on 2024-10-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vparnter', '0018_alter_vehiclecategory_weight_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='load_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
