# Generated by Django 5.0.6 on 2024-10-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vparnter', '0019_alter_vehicle_load_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecategory',
            name='image',
            field=models.ImageField(default='unknown', upload_to='vehicle_category_images/'),
            preserve_default=False,
        ),
    ]
