# Generated by Django 5.0.6 on 2024-10-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vparnter', '0021_drivernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivernotification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
