# Generated by Django 5.0.6 on 2024-10-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vparnter', '0022_drivernotification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_purpose',
            field=models.CharField(choices=[('passenger', 'Passenger'), ('logistics', 'Logistics'), ('ambulance', 'Ambulance')], default='logistics', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='weight_category',
            field=models.IntegerField(choices=[(1, '0 to 100 kg'), (2, '0 to 250 kg'), (3, '0 to 650 kg'), (4, '0 to 1000 kg'), (5, '0 to 1500 kg'), (6, '0 to 2000 kg'), (7, 'Passenger'), (8, 'Ambulance')], unique=True),
        ),
    ]
