# Generated by Django 5.0.6 on 2024-11-02 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_feedback_order_alter_feedback_description_and_more'),
        ('vparnter', '0023_alter_vehicle_vehicle_purpose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_times', to='customer.order')),
            ],
        ),
    ]
