# Generated by Django 5.0.6 on 2024-11-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vparnter', '0024_waitingtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingtime',
            name='waiting_time_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
