# Generated by Django 5.0.6 on 2024-09-24 05:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_sliderimage'),
        ('vparnter', '0012_alter_vehicle_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=15, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('item_name', models.CharField(max_length=255)),
                ('load_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('load_image', models.ImageField(upload_to='load_images/')),
                ('services', models.CharField(max_length=255)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processing_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vparnter.partnerinfo')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vparnter.vehicle')),
            ],
        ),
    ]
