# Generated by Django 5.0.6 on 2024-09-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('running', 'Running'), ('booking', 'Booking'), ('confirm', 'Confirm'), ('cancel', 'Cancel')], default='booking', max_length=10),
        ),
    ]
