# Generated by Django 5.0.6 on 2024-09-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='home_place',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='work_place',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
