# Generated by Django 5.0.6 on 2024-10-01 04:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_customer_home_place_alter_customer_work_place'),
        ('vparnter', '0016_vehiclecategory_pricing_loadpricing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField(blank=True, max_length=500)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vparnter.partnerinfo')),
            ],
        ),
    ]
