# Generated by Django 5.0.6 on 2024-10-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='otp',
            field=models.CharField(default=1, editable=False, max_length=4),
            preserve_default=False,
        ),
    ]
