# Generated by Django 5.0.6 on 2024-10-16 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_customer_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='platform_fee',
        ),
        migrations.AddField(
            model_name='order',
            name='labor_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ViaLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='via_locations', to='customer.order')),
            ],
        ),
    ]
