# Generated by Django 5.0.6 on 2024-10-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_remove_order_platform_fee_order_labor_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
