# Generated by Django 5.0.6 on 2024-10-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_order_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('booking', 'Booking'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='booking', max_length=15),
        ),
    ]
