# Generated by Django 5.0.6 on 2024-10-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_order_otp_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='load_image',
            field=models.ImageField(blank=True, null=True, upload_to='load_images/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='load_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
