# Generated by Django 5.0.6 on 2024-10-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_alter_order_load_image_alter_order_load_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
