# Generated by Django 5.0.6 on 2024-10-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_order_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
