# Generated by Django 5.0.6 on 2024-10-29 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_order_otp_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
