# Generated by Django 5.0.6 on 2024-11-03 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_feedback_order_alter_feedback_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('notification_type', models.CharField(choices=[('order_update', 'Order Update'), ('payment_notification', 'Payment Notification'), ('promotional', 'Promotional'), ('general', 'General'), ('important', 'Important')], default='general', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='customer.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
