# Generated by Django 5.0.6 on 2024-09-24 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Employee ID must be in the format EHASCDDXXX', regex='^EHASCD[A-Z]{3}$')])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('joining_date', models.DateField()),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
